SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS AmministratorE;
DROP TABLE IF EXISTS Storico;
DROP TABLE IF EXISTS Dipendente;
DROP TABLE IF EXISTS Domanda;
DROP TABLE IF EXISTS RuolO;
DROP TABLE IF EXISTS Badge;
DROP TABLE IF EXISTS Assegnato;

CREATE TABLE Amministratore(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	nickname VARCHAR(25) NOT NULL,
	password CHAR(32) NOT NULL,
	passmod CHAR(32),
	datapass DATE,
	codfisc INT(11) NOT NULL,
	tipoamm BOOL DEFAULT FALSE
)ENGINE=InnoDB;

CREATE TABLE Dipendente(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	cognome VARCHAR(255) NOT NULL,
	codfisc CHAR(16) NOT NULL,
	email VARCHAR(255) NOT NULL,
	nickname VARCHAR(25) NOT NULL,
	password CHAR(32) NOT NULL,
	passmod CHAR(32) NOT NULL,
	ruolo VARCHAR(255),
	badge INT DEFAULT '0',
	
	FOREIGN KEY ruolo REFERENCES Ruolo(ruolo)
						ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE Storico(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	IDdomanda INT NOT NULL,
	IDdipendente INT NOT NULL,
	risposta BOOL DEFAULT FALSE,
	corretta BOOL DEFAULT FALSE,
	punteggio INT DEFAULT '0',
	
	FOREIGN KEY(IDdomanda) REFERENCES Domanda(ID)
							ON UPDATE CASCADE,
	FOREIGN KEY(IDdipendente) REFERENCES Dipendente(ID)
							ON UPDATE CASCADE
							ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE Domanda(
	ID INT PRIMARY KEY NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Ruolo(
	ruolo VARCHAR(255) PRIMARY KEY NOT NULL
)ENGINE=InnoDB;


CREATE TABLE Assegnato(
	IDDipendente INT PRIMARY KEY NOT NULL,
	IDBadge INT PRIMARY KEY NOT NULL,
	data DATE NOT NULL,
	
	FOREIGN KEY(IDDipendente) REFERENCES Dipendente(ID)
								ON UPDATE CASCADE,
	FOREIGN KEY(IDBadge) REFERENCES Badge(ID)
							ON UPDATE CASCADE
							ON DELETE CASCADE
	
)ENGINE=InnoDB;

CREATE TABLE Badge(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	descrizione VARCHAR(max) NOT NULL
)ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=1;
